language: python
python:
#- 2.6
- 2.7
# command to install dependencies
services: postgresql
env:
- DJANGO=1.11.2

before_install:
- export DJANGO_SETTINGS_MODULE=your_project.settings
- export PYTHONPATH=$HOME/builds/your_github_username/your_repo
- export PIP_USE_MIRRORS=true

install:
#- pip install -r requirements.txt
#- pip install django==$DJANGO --quiet
#- pip install django==$DJANGO.1.11.2  #	_VERSION 
#- python setup.py -q install
#- pip install psycopg2 --quiet

before_script:
- psql -c "CREATE DATABASE mydb;" -U postgres

# script: pytest
#- python manage.py syncdb --noinput
