language: python

python:
#- 2.6
- 2.7

services: postgresql

env:
- DJANGO=1.11.2

#before_install:
#- export DJANGO_SETTINGS_MODULE=myblog.settings
#- export PYTHONPATH=$HOME/builds/kirubeltadesse/Website
#- export PIP_USE_MIRRORS=true

install:
#- pip install -r requirements.txt
- pip install django==$DJANGO --quiet
#- pip install psycopg2 --quiet

before_script:
- python manage.py runserver &
- psql -c "CREATE DATABASE mydb;" -U postgres

script: 
#- coverage python manage.py syncdb #--noinput
- python manage.py makemigrations
- python manage.py migrate 
- python manage.py test myblog

skip_build:
- docs/*
- README.md
- LICENSE
